name: Notificar a ntfy.sh cuando haya push

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificaci√≥n a ntfy.sh
        run: |
          curl -d "Se hizo un push al repositorio main de CI Hola Mundo Ì∫Ä" \
          -H "Title: Nuevo Push a CI" \
          -H "Priority: 5" \
          https://ntfy.sh/devops-itla


